/** \file main.c
    \brief PSP decode smoke test: does libpxlcore build for the real target and
           decode correctly there, one case per color filter.

    This is deliberately NOT a throughput benchmark. sceRtcGetCurrentTick is
    read around each decode and printed, but under PPSSPPHeadless that number
    times the emulator's own JIT, not the 222/333 MHz Allegrex core -- see
    RESEARCH.md for why this project treats an emulator timing as untrustworthy
    for a hardware throughput claim. What this program actually establishes:
    the codec cross-compiles for MIPS with psp-gcc, links against PSPSDK's
    newlib, and reconstructs each filter's pixels bit-exact on that target.
    The timing line is printed anyway so the same binary needs no changes once
    it runs on real hardware -- at that point the printed microseconds become
    the number ROADMAP.md asks for.

    Test data (psp/testdata.h, generated by bench/mkpsptest.c) is compiled
    into the binary rather than read from a memory stick, so this runs
    unattended under PPSSPPHeadless with no virtual filesystem to set up.

    Output goes through sceIoWrite(1, ...) rather than printf/stdout: this is
    the same primitive PPSSPP's own "pspautotests" suite uses, and headless
    mode is documented to capture it ("emulated printfs") without any extra
    setup. Plain libc stdout was not used because whether it is line-buffered,
    fully buffered, or wired to fd 1 at all depends on newlib's startup code in
    a way this project has not verified -- sceIoWrite is one layer lower and
    leaves nothing to that assumption.
*/
#include <pspkernel.h>
#include <psprtc.h>

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include "pxl.h"
#include "testdata.h"

PSP_MODULE_INFO("PXLBENCH", 0, 1, 0);
PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER);

static void put(const char* s)
{
    sceIoWrite(1, s, strlen(s));
}

static void putf(const char* fmt, ...)
{
    char buf[256];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof buf, fmt, ap);
    va_end(ap);
    put(buf);
}

typedef struct {
    const char*          name;
    const unsigned char* data;
    unsigned int         len;
} pxl_psp_case;

int main(void)
{
    static const pxl_psp_case cases[] = {
        { "none",     pxl_psp_file_none,     pxl_psp_file_none_len },
        { "delta",    pxl_psp_file_delta,    pxl_psp_file_delta_len },
        { "adaptive", pxl_psp_file_adaptive, pxl_psp_file_adaptive_len },
        { "bcif",     pxl_psp_file_bcif,     pxl_psp_file_bcif_len },
    };
    unsigned i;
    int all_ok = 1;

    putf("PXL PSP decode smoke test, libpxl %s\n", pxl_version());
    putf("(timings below are emulator microseconds if run under PPSSPPHeadless,\n"
         " not Allegrex hardware time -- see psp/README.md)\n");

    for (i = 0; i < sizeof cases / sizeof cases[0]; i++) {
        pxl_buffer file;
        pxl_image  img;
        u64        t0 = 0, t1 = 0;
        int        match;

        file.data = (unsigned char*)cases[i].data;
        file.size = cases[i].len;

        sceRtcGetCurrentTick(&t0);
        img = pxl_decode(file);
        sceRtcGetCurrentTick(&t1);

        if (!img.buffer.data) {
            putf("[%-8s] DECODE FAILED\n", cases[i].name);
            all_ok = 0;
            continue;
        }

        match = img.buffer.size == pxl_psp_expected_pixels_len &&
                memcmp(img.buffer.data, pxl_psp_expected_pixels, img.buffer.size) == 0;
        if (!match) {
            all_ok = 0;
        }

        putf("[%-8s] %ux%u %uch %u bytes in %u us -- %s\n",
             cases[i].name, (unsigned)img.width, (unsigned)img.height,
             (unsigned)img.channels, (unsigned)img.buffer.size,
             (unsigned)(t1 - t0), match ? "MATCH" : "MISMATCH");

        pxl_image_free(&img);
    }

    put(all_ok ? "ALL OK\n" : "SOME FAILED\n");
    sceKernelExitGame();
    return 0;
}
